### PR TITLE
updated project and binaries 

### PR DESCRIPTION
**Pull request by jorisdejong**
Updated solution to VS2019
Rebuilt binaries for Arena 7.0.5

no other changes

### CODE REVIEW

**Comment by jorisdejong** [comment]
I think most people are looking for the binaries in Github's releases tab. Apparently, these don't get included in the pull request, so maybe you can upload them yourself.

**Comment by DanielArnett** [comment]
Is there a specific version of Resolume, or some software that it wasn't compatible with before this update? In other words what should I put on the update for this release? Do I need to compile similar binaries for OSX?

**Comment by jorisdejong** [comment]
I tried running the dlls that were under version control in 'binaries', but
they don't load in Arena 7.0.5. After compiling, the resulting dlls do. I'm
not sure what changed. For consistency, I'd tag the release as 7.0.0

I didn't get a chance to look at OSX yet.

**Comment by DanielArnett** [comment]
Good to know, thanks for updating it!

**Comment by DanielArnett** [comment]
[Updated](https://github.com/DanielArnett/360-VJ/releases/tag/7.0.0), thanks!

**Pull request merged**
