### PR TITLE
Mac build

### PR DESCRIPTION
**Pull request by xinaesthete**
as per #5 

I couldn't get the ffgl submodule to work without removing ffgl1.5.

### CODE REVIEW

**Comment by xinaesthete** [comment]
I've just noticed some binary files managed to sneak their way in to that last commit... how irritating.

**Comment by DanielArnett** [comment]
@xinaesthete Can I ask you to redo this with the new main branch? I updated/rebased the code off of Resolume's latest commits for their plugins. Now all of the conversions are packed into a single effect that can seamlessly rotate and convert between fisheye, equirectangular, and flat video projections. It also fixes some of the bugs that the old code had, and the shader is much easier to read now that it's in its own separate file.

**Comment by xinaesthete** [comment]
Just starting to look into this. Having the shader code in a separate file seems like a good step (I've been toying with the idea of watching shader files and automatically re-compiling).

Right now I'm just trying to figure out why I'm not seeing your recent commits in VSCode... I guess once I figure out what's going on with git it should be less work to redo (and maintain) since there'll only be the one target to configure.

**Comment by DanielArnett** [comment]
I switched the default branch to main because I was doing some serious
changes, and I didn't want to break master.

**Comment by DanielArnett** [comment]
To help you debug, you can also use the [simple-shader branch](https://github.com/DanielArnett/360-VJ/compare/simple-shader?expand=1). It's the original AddSubtract example provided by resolume, and not split out into its own file (in case that causes compiler errors on OSX). It might be easier to get the simple-shader branch building on OSX before you fuss with the full shader. Then you can `git checkout main; git pull` and try the full shader.

**Comment by xinaesthete** [comment]
Good news - the only thing I needed to do to get your new main branch to build was change a few `sprintf_s`s to `sprintf`. No need for repeating any of the steps I'd taken previously of reconfiguring Xcode project.

I didn't test at all extensively, debug build still crashes Resolume (as it does with the upstream AddSubtract example), but doing an 'Archive' and extracting the `AddSubtract.bundle` from there appears to be working.

**Comment by xinaesthete** [comment]
Closing, see https://github.com/DanielArnett/360-VJ/pull/9

**Pull request closed without merging**
